server:
  port: 8021
spring:
  application:
    name: cloud-consumer-feign-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true
#    # 默认为true。如果设置为false，Ribbon将
#  不会从Eureka中获得服务列表，⽽是使⽤静态配置的服务列表。静态服务列表可使
#  ⽤：<client>.ribbon.listOfServers来指定。参考：http://projects.s
#  pring.io/spring-cloud/docs/1.0.3/spring-cloud.html#spring-clo
#  ud-ribbon-without-eureka