spring:
  application:
    name: cloud-hystrix-turbine
server:
  port: 8031
security:
  basic:
    enabled: false
turbine:
  aggregator:
    clusterConfig: default
  app-config: cloud-consumer-ribbon-hystrix,cloud-consumer-feign-hystrix
  ### 配置Eureka中的serviceId列表，表明监控哪些服务
  cluster-name-expression: new String("default")
#  # 1. clusterNameExpression指定集群名称，默认表达式appName；此时：
#  turbine.aggregator.clusterConfig需要配置想要监控的应⽤名称
#  # 2. 当clusterNameExpression: default时，turbine.aggregator.
#  clusterConfig可以不写，因为默认就是default
#  # 3. 当clusterNameExpression: metadata['cluster']时，假设想要
#  监控的应⽤配置了eureka.instance.metadata-map.cluster: ABC，则需要
#  配置，同时turbine.aggregator.clusterConfig: ABC
eureka:
  client:
    service-url:
      default-zone: http://discovery:8761/eureka/

